baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "missioncharge"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "missioncharge"
  subtitle    = "All things electric "

  cover       = "img/blog-cover.jpg"
  description = "ALL things electric"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "belalthecoolboy"
  fbName = "belalthecoolboy"
  githubName = "beellz"

  logo = "upload/BZ.png"
  orgName = "EM"
  orgWebsite = "Missioncharge"
  orgDescription = "ALL Things Electric"

  author = "BZ"
  authorAvatar = "upload/logo-avatar.jpg"
  authorLocation = "Mumbai , India"
  authorWebsite = "https://missioncharge.com"
  authorDescription = "beliver of electric"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "projects"
  url = "/projects"
  weight = 100

[[menu.main]]
  name = "article"
  url = "/article"
  weight = 99

[[menu.main]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UC7xs-jRRKH_1piJv2HiC1bA"
  weight = 95